version: '1.0'

services:
  # Base de datos PostgreSQL
  - name: bot-whatsapp-db
    type: postgres
    version: '14'
    environment:
      POSTGRES_DB: botwhatsapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - name: postgres-data
        mount: /var/lib/postgresql/data
    resources:
      memory: 512Mi
      cpu: 0.5

  # Servidor Baileys (WhatsApp)
  - name: bot-whatsapp-baileys
    type: app
    source:
      type: github
      repo: ${GITHUB_REPO}
      branch: main
    build:
      dockerfile: Dockerfile.baileys
    deploy:
      replicas: 1
      resources:
        memory: 512Mi
        cpu: 0.5
    ports:
      - port: 3001
        protocol: http
    environment:
      NODE_ENV: production
      PORT: 3001
      SESSION_PATH: /data/whatsapp-sessions
    volumes:
      - name: whatsapp-sessions
        mount: /data/whatsapp-sessions
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Python (API y Bot)
  - name: bot-whatsapp-python
    type: app
    source:
      type: github
      repo: ${GITHUB_REPO}
      branch: main
    build:
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        memory: 1Gi
        cpu: 1
    ports:
      - port: 5000
        protocol: http
        public: true
    environment:
      # Base de datos
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@bot-whatsapp-db:5432/botwhatsapp
      
      # IA - GROQ
      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_API_KEY_2: ${GROQ_API_KEY_2}
      GROQ_API_KEY_6: ${GROQ_API_KEY_6}
      GROQ_MODEL: llama-3.1-8b-instant
      GROQ_ENABLED: true
      ENABLE_GROQ_ROTATION: true
      
      # IA - OpenAI (opcional)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ENABLED: false
      
      # Negocio
      BUSINESS_NAME: ${BUSINESS_NAME}
      BUSINESS_PHONE: ${BUSINESS_PHONE}
      BUSINESS_EMAIL: ${BUSINESS_EMAIL}
      BOT_NAME: ${BOT_NAME}
      
      # Pagos
      NEQUI_NUMBER: ${NEQUI_NUMBER}
      DAVIPLATA_NUMBER: ${DAVIPLATA_NUMBER}
      BANK_NAME: ${BANK_NAME}
      BANK_ACCOUNT_NUMBER: ${BANK_ACCOUNT_NUMBER}
      MERCADOPAGO_ACCESS_TOKEN: ${MERCADOPAGO_ACCESS_TOKEN}
      MERCADOPAGO_ENABLED: true
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
      PAYPAL_ENABLED: true
      
      # Email
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      
      # Dropshipping
      DROPI_AGENT_TOKEN: ${DROPI_AGENT_TOKEN}
      DROPI_ENABLED: true
      
      # Funcionalidades
      ENABLE_PROFESSIONAL_SALES: true
      AUTO_SEND_PHOTOS: true
      SMART_PHOTOS_ENABLED: true
      TTS_ENABLED: true
      VISION_AI_ENABLED: true
      OCR_ENABLED: false
      PHOTOS_ENABLED: true
      AUDIO_ENABLED: true
      
      # Sistema
      PYTHONUNBUFFERED: 1
      PORT: 5000
      LOG_LEVEL: info
      
    volumes:
      - name: whatsapp-sessions
        mount: /data/whatsapp-sessions
      - name: temp-media
        mount: /app/temp-media
    depends_on:
      - bot-whatsapp-db
      - bot-whatsapp-baileys
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  - name: postgres-data
    size: 5Gi
  - name: whatsapp-sessions
    size: 2Gi
  - name: temp-media
    size: 1Gi
